package io.ra6.zephyr.codeanalysis.binding;

public enum BoundNodeKind {
    EXPRESSION_STATEMENT,
    ERROR_EXPRESSION,
    LITERAL_EXPRESSION,
    BINARY_EXPRESSION,
    CONDITIONAL_EXPRESSION,
    INSTANCE_CREATION_EXPRESSION,
    VARIABLE_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    FIELD_ACCESS_EXPRESSION,
    MEMBER_ACCESS_EXPRESSION,
    METHOD_CALL_EXPRESSION,
    IF_STATEMENT,
    GOTO_STATEMENT,
    CONDITIONAL_GOTO_STATEMENT,
    LABEL_STATEMENT,
    WHILE_STATEMENT,
    RETURN_STATEMENT,
    VARIABLE_DECLARATION,
    UNARY_EXPRESSION, THIS_EXPRESSION, TYPE_EXPRESSION, INTERNAL_FUNCTION_EXPRESSION, METHOD_ACCESS_EXPRESSION, BLOCK_STATEMENT
}
